root: true
parser: '@typescript-eslint/parser'
parserOptions:
  project:
    - './tsconfig.json'
    - './tsconfig.test.json'
  ecmaVersion: 2020
  sourceType: 'module'
plugins:
  - '@typescript-eslint'
  - 'prettier'
  - 'import'
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:import/errors'
  - 'plugin:import/warnings'
  - 'plugin:import/typescript'
  - 'plugin:prettier/recommended'
  - 'prettier'
env:
  node: true
  jest: true
ignorePatterns:
  - 'node_modules/'
  - 'dist/'
  - 'coverage/'
  - 'jest.config.ts'
rules:
  '@typescript-eslint/explicit-module-boundary-types': 'warn'
  '@typescript-eslint/no-explicit-any': 'warn'
  '@typescript-eslint/no-unused-vars':
    - 'error'
    - argsIgnorePattern: '^_'
      varsIgnorePattern: '^_'
  'no-console': 'warn'
  'prettier/prettier': 'error'
  'import/order':
    - 'error'
    - groups:
        - 'builtin'
        - 'external'
        - 'internal'
        - 'parent'
        - 'sibling'
        - 'index'
        - 'object'
        - 'type'
      newlines-between: 'always'
      alphabetize:
        order: 'asc'
        caseInsensitive: true
      pathGroups:
        - pattern: '{src/**}'
          group: 'internal'
          position: 'after'
  'sort-imports':
    - 'error'
    - ignoreDeclarationSort: true
      ignoreMemberSort: false
  'import/no-unresolved': 'error'
  'import/named': 'error'
settings:
  'import/resolver':
    'typescript':
      alwaysTryTypes: true
      project:
        - './tsconfig.json'
        - './tsconfig.test.json' 
